name: Build client and server bundles for dummy app with Webpack and save them to cache

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby: [2.6]
        node: [12]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Setup Node
      uses: actions/setup-node@v1.4.3
      with:
        node-version: ${{ matrix.node }}
    - name: Print system information
      run: |
        echo "Linux release: "; cat /etc/issue
        echo "Current user: "; whoami
        echo "Current directory: "; pwd
        echo "Ruby version: "; ruby -v
        echo "Node version: "; node -v
        echo "Yarn version: "; yarn --version
        echo "Bundler version: "; bundle --version
    - name: Save root node_modules to cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: v4-package-node-modules-cache-${{ hashFiles('yarn.lock') }}
    - name: Install Node modules with Yarn for renderer package
      run: |
        yarn install --no-progress --no-emoji
        yarn run eslint -v
        sudo yarn global add yalc
    - name: yalc publish for react-on-rails
      run: yalc publish
    - name: Save spec/dummy/node_modules to cache
      uses: actions/cache@v2
      with:
        path: spec/dummy/node_modules
        key: v4-dummy-app-node-modules-cache-${{ hashFiles('spec/dummy/yarn.lock') }}
    - name: yalc add react-on-rails
      run: cd spec/dummy && yalc add react-on-rails
    - name: Install Node modules with Yarn for dummy app
      run: cd spec/dummy && yarn install --no-progress --no-emoji
    - name: Save dummy app ruby gems to cache
      uses: actions/cache@v2
      with:
        path: spec/dummy/vendor/bundle
        key: v4-dummy-app-gem-cache-${{ hashFiles('spec/dummy/Gemfile.lock') }}
    - name: Install Ruby Gems for dummy app
      run: cd spec/dummy && bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
    - name: Build test bundles for dummy app
      run: cd spec/dummy && yarn run build:test
    - id: get-sha
      run: echo "::set-output name=sha::$(git rev-parse HEAD)"
    - name: Save test webpack bundles to cache (for build number checksum used by rspec job)
      uses: actions/cache@v2
      with:
        path: spec/dummy/public/webpack
        key: v4-dummy-app-webpack-bundle-${{ steps.get-sha.outputs.sha }}
